spring:
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: wangjianloveblue@163.com
    password: w**5
    properties:
      smtpAuth: true
      smtpStarttlsEnable: true
      smtpStarttlsRequired: true
      smtpSslTrust: smtp.163.com